# Generated by Django 5.2.5 on 2025-08-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='discount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='customers.customer', verbose_name='Customer'),
        ),
    ]
