# Generated by Django 5.2.5 on 2025-08-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Visit'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_discount_active',
            field=models.BooleanField(default=False, verbose_name='Loyalty Discount Active'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_discount_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Loyalty Discount Expires'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_discount_percentage',
            field=models.PositiveIntegerField(default=10, verbose_name='Loyalty Discount Percentage'),
        ),
        migrations.AddField(
            model_name='customer',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visit Count'),
        ),
    ]
