# Generated by Django 5.2.5 on 2025-08-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Current Stock')),
                ('minimum_stock', models.PositiveIntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('is_low_stock', models.BooleanField(default=False, verbose_name='Low Stock Alert')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='menu.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['product__name'],
            },
        ),
    ]
