# Generated by Django 5.2.5 on 2025-08-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_inventory'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Sales')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Order Count')),
                ('customer_count', models.PositiveIntegerField(default=0, verbose_name='Customer Count')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Average Order Value')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Discounts')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Net Revenue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Quantity Sold')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Revenue')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Order Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='menu.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Analytics',
                'verbose_name_plural': 'Product Analytics',
                'ordering': ['-date', '-total_revenue'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
